import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ProductWrapper from '../components/ProductWrapper'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <ProductWrapper products={[1, 2, 3]} />
      </main>
    </div>
  )
}
